when@dev:
    monolog:
        channels:
            - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        handlers:
            filter_for_errors:
                type: fingers_crossed
                action_level: error
                handler: main
                channels: ["!event", "!doctrine"]
            main:
                type: stream
                path: php://stderr
                level: debug
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

